{{- if and .Values.enabledRBAC (not .Values.serviceAccountName) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ default (include "app.fullname" .) .Values.serviceAccountNameOverride }}
imagePullSecrets: 
{{ toYaml .Values.image.pullSecrets | indent 2 }}

---
apiVersion: {{ template "rbac_api_version" . }}
kind: ClusterRole
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ include "app.fullname" . }}-{{ .Release.Namespace }}
rules:
- nonResourceURLs: 
  - "/metrics"
  verbs:
  - "get"
- apiGroups:
  - "extensions"
  verbs: 
  - "list"
  - "watch"
  resources:
  - ingresses
- apiGroups: 
  - ""
  verbs: 
  - "list"
  - "watch"
  resources:
  - services
  - endpoints
  - pods
{{- if eq .Values.level "cluster" }}
  - nodes
- apiGroups:
  - ""
  resources:
  - nodes/metrics
  verbs:
  - "get"
- apiGroups:
  - ""
  resources:
  - namespaces
  - secrets
  verbs:
  - "list"
  - "watch"
  - "get"
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - "create"
{{- end }}

---
apiVersion: {{ template "rbac_api_version" . }}
kind: ClusterRoleBinding
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ include "app.fullname" . }}-{{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "app.fullname" . }}-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ default (include "app.fullname" .) .Values.serviceAccountNameOverride }}
    namespace: {{ .Release.Namespace }}

{{- if eq .Values.level "project" }}
---
apiVersion: {{ template "rbac_api_version" . }}
kind: Role
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ include "app.fullname" . }}
rules:
- apiGroups:
  - "monitoring.cattle.io"
  resources:
  - prometheus
  verbs:
  - "view"

---
apiVersion: {{ template "rbac_api_version" . }}
kind: RoleBinding
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ include "app.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "app.fullname" . }}
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ default (include "app.fullname" .) .Values.serviceAccountNameOverride }}
    namespace: {{ .Release.Namespace }}
{{- end }}

{{- $projectId :=  index (index .Values.serviceMonitorNamespaceSelector.matchExpressions 0).values 0 }}
{{- $appServiceAccountName := default (include "app.fullname" .) .Values.serviceAccountNameOverride }}
{{- $appName := include "app.name" . }}
{{- $appVersion := include "app.version" . }}
---
apiVersion: {{ template "rbac_api_version" . }}
kind: ClusterRoleBinding
metadata:
  labels:
    app: {{ $appName }}
    chart: {{ $appVersion }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ $projectId }}-namespaces-readonly-additional-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $projectId }}-namespaces-readonly
subjects:
  - kind: ServiceAccount
    name: {{ $appServiceAccountName }}
    namespace: {{ .Release.Namespace }}

{{- end }}
